name: Unit tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:

      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Start Timer
        run: echo "::set-output start_time=$(date +%s)" >> $GITHUB_ENV

      - name: Build and Run Tests
        id: run-tests
        run: ./gradlew test

      - name: Record End Time and Calculate Duration
        id: end-and-duration
        run: |
          end_time=$(date +%s)
          duration=$(( end_time - ${{ env.start_time }} ))
          echo "::set-output end_time=$end_time" >> $GITHUB_ENV
          echo "::set-output duration=$duration" >> $GITHUB_ENV

      - name: Determine Test Status
        id: determine-status
        run: |
          if [ "${{ steps.run-tests.conclusion }}" == "success" ]; then
            echo "::set-output status=success" >> $GITHUB_ENV
          else
            echo "::set-output status=failure" >> $GITHUB_ENV
          fi